version: '3.8'

services:
  spring-app:
    build: .
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/restaurante
    ports:
      - '3000:80'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
